test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir", "install.nourl", "install.multi"]  # The test IDs to be used in only/exclude statements are: install.root, install.subdir, install.nourl, install.multi, backup_restore, upgrade, upgrade.someCommitId change_url
    # NB: you should NOT need this except if you really have a good reason...

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.password = "acab1312"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.00a1a6e7.name = "Upgrade from 5.4"
    # test_upgrade_from.00a1a6e7.args.foo = "bar"
